// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9cVZC8vhQqQnbhE1b9KaPp9G7zCTjEJg',
    appId: '1:461933808178:web:a0f24081e99e8cb2928a2b',
    messagingSenderId: '461933808178',
    projectId: 'flutter-4a402',
    authDomain: 'flutter-4a402.firebaseapp.com',
    storageBucket: 'flutter-4a402.firebasestorage.app',
    measurementId: 'G-G0R3SLRY15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt042eS-oB6izN_tmHARj3vC5SZjcwiL4',
    appId: '1:461933808178:android:6da46bf19b209e07928a2b',
    messagingSenderId: '461933808178',
    projectId: 'flutter-4a402',
    storageBucket: 'flutter-4a402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI0_NqdopZDGuyHJ8lwrzgTjcTFwObgAA',
    appId: '1:461933808178:ios:5e9e8abdf1be2fc9928a2b',
    messagingSenderId: '461933808178',
    projectId: 'flutter-4a402',
    storageBucket: 'flutter-4a402.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI0_NqdopZDGuyHJ8lwrzgTjcTFwObgAA',
    appId: '1:461933808178:ios:5e9e8abdf1be2fc9928a2b',
    messagingSenderId: '461933808178',
    projectId: 'flutter-4a402',
    storageBucket: 'flutter-4a402.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9cVZC8vhQqQnbhE1b9KaPp9G7zCTjEJg',
    appId: '1:461933808178:web:30aa363d38db82af928a2b',
    messagingSenderId: '461933808178',
    projectId: 'flutter-4a402',
    authDomain: 'flutter-4a402.firebaseapp.com',
    storageBucket: 'flutter-4a402.firebasestorage.app',
    measurementId: 'G-KDT5VGQ2RD',
  );
}
